stages:
  - publish

build:
  stage: publish
  pages:
    publish: dist
  image: node:22-alpine
  before_script:
    - yarn install
  script:
    - yarn build
  artifacts:
    paths:
      - dist
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
